### ISSUE TITLE
kamailio+dispatcher pod restarting frequently 

### ISSUE THREAD

**Issue by sivachirravuri** [CyCoreSystems/dispatchers#1]
HI
My Pod containing kamailio and dispatcher containers is getting restarted multiple times.
dispatcher container just throws the following error
 
"failed to maintain dispatcher sets: error maintaining sets: failure during watch: EOF"

Please help..

**Comment by Ulexus** [comment]
This is "normal" and I need to fix it.  Essentially, the watch connection to the API server is timing out, which is completely normal.  However, right now dispatchers exits when this happens.  It should just reconnect.  This will involve wrapping the watch process and handling the timeout gracefully.

**Comment by Ulexus** [comment]
This _should_ take care of it; let me know how it goes for you.

**Comment by sivachirravuri** [comment]
Its fine now.. Thanks for the quick help.
