### ISSUE TITLE
Need support

### ISSUE THREAD

**Issue by belvarr** [CyCoreSystems/dispatchers#3]
Would you please provide us with more details or description for the way the dispatchers work.
could you draw a simple diagram for kamailio and asterisk pod  reload dispatched mechanism through the Kubernetes.

Thanks in advance

**Comment by Ulexus** [comment]
@belvarr Sorry that I failed to see this request until just now.

The dispatchers tool monitors the Endpoints for a set of Kubernetes Services (generally, these would be Asterisk or FreeSWITCH boxes).  When the list of Endpoints changes, it writes out a new `dispatchers` file for Kamailio and then tells Kamailio (using its binrpc protocol) to reload that file.

**Comment by Ulexus** [comment]
The documentation for the Kamailio dispatcher module can be found [here](https://kamailio.org/docs/modules/stable/modules/dispatcher.html)
