### ISSUE TITLE
API end point to get all the dispatcher sets

### ISSUE THREAD

**Issue by yair-voca** [CyCoreSystems/dispatchers#4]
We would like to be able to get all the dispatcher sets from external application over rest request.
what do you think about this?
would you accept if we will do the work and make a pull request?  

@danjenkins 

Thanks.

**Comment by Ulexus** [comment]
This sounds perfectly reasonable to me.

**Comment by yair-voca** [comment]
Pull request created.

Thanks.

**Comment by yair-voca** [comment]
Thanks for your approval, could you please build new image and publish it to:
https://hub.docker.com/r/cycoresystems/dispatchers/

We very need this...

Thanks

**Comment by Ulexus** [comment]
Travis will automatically do this shortly.  I just pushed version v1.2.1, which includes a bit of restructuring for the API service.  Thanks

**Comment by yair-voca** [comment]
**Thanks for the fast helping!**
Small note: It think that the next comment is no longer true- (the default is to run..) 
https://github.com/CyCoreSystems/dispatchers/blob/67395bfcd164d5c4ef0e134e9fcf35e94139bce0/main.go#L51

**Comment by Ulexus** [comment]
It should be still true:

https://github.com/CyCoreSystems/dispatchers/blob/67395bfcd164d5c4ef0e134e9fcf35e94139bce0/main.go#L252

**Comment by yair-voca** [comment]
I missed this condition..😅
Thanks!

בתאריך יום ג׳, 12 במאי 2020, 22:07, מאת Seán C. McCord ‏<
notifications@github.com>:
