### ISSUE TITLE
New end point for fetching dispatcher set list not working for dynamic k8s sets

### ISSUE THREAD

**Issue by yair-voca** [CyCoreSystems/dispatchers#6]
HI @Ulexus, 
After testing it I found that when I trying to get a dynamic k8s dispatcher set list I got an empty json object- {}

When I trying to fetch a static set list everything is good, for example you can see the next response:
{"Members":["XXX.XX.XXX.XX:5060"]} 

I think this issue is related to the fact that the implementation of "kubernetesSet" (7 parameters) is different from the implementation of "staticSet" (2 parameters).

But, with the fact that you are using an interface I can't really understand what is the specific problem.

Maybe in case of dynamic k8s set we should return from "getDispatcherSet" method a new instance of "staticSet" and initiate him with the relevant "members" from the dynamic set-
What do you think?

**I will very appreciate your help with that.**

Thanks!

@danjenkins

**Comment by Ulexus** [comment]
Sorry about that; you are quite right.  This should fix it.

**Comment by yair-voca** [comment]
Now it's working..
Thanks a lot for the fast response!
