### ISSUE TITLE
dispatchers pod fail to create

### ISSUE THREAD

**Issue by marayshi** [CyCoreSystems/dispatchers#7]
I see this error when " kubectl describe pod/kamailio-deployment-c4b6fbf4-vd9nq"

`Error: failed to start container "dispatchers": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app": stat /app: no such file or directory: unknown`

Can i set the dispacher.list path to the default /etc/kamailio/dispatcher.list ?

**Comment by marayshi** [comment]
Hi @Ulexus 

Can you advice please ?

**Comment by marayshi** [comment]
I fixed the issue by changing the command to this

```
          command:
            - /go/bin/dispatchers
            - "-set"
            - default:asterisk=1:5080
```

**Comment by Ulexus** [comment]
Ah, yep.  I should change that example to use `args:` instead.  I changed
